# -*- coding: utf-8 -*-
"""ОИИС_lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pa0iWbEScqlEkF0MAw5Wd6mXws5MsbaB
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="PPvWh3zYDUwdXSmGOJai")
project = rf.workspace("roboflow-100").project("vehicles-q0x2v")
version = project.version(2)
dataset = version.download("yolov11")

!pip install ultralytics -q

from ultralytics import YOLO
import os
from google.colab import files

model = YOLO("yolo11s.pt")

import torch
device = 0 if torch.cuda.is_available() else "cpu"

model.train(
    data=f"{dataset.location}/data.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    device=device,
)

drive.mount('/content/drive')

uploaded = files.upload()

results = model.predict(
    source=list(uploaded.keys())[0],
    conf=0.25,
    save=True
)

files.download("runs/")

!zip -r my_yolo_model.zip /content/runs/detect/train/

files.download('my_yolo_model.zip')