# -*- coding: utf-8 -*-
"""lab5_ИАД.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10sZTgi3iHxBwkyVKc_lnWqfpuSUHuxrj
"""

!pip install xgboost catboost matplotlib seaborn

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("glass.csv")

X = df.drop("Type", axis=1)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(df["Type"])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "AdaBoost": AdaBoostClassifier(n_estimators=200, random_state=42),
    "XGBoost": XGBClassifier(n_estimators=200, random_state=42, eval_metric='mlogloss', use_label_encoder=False),
    "CatBoost": CatBoostClassifier(iterations=200, verbose=0, random_seed=42)
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    results[name] = {"model": model, "acc": acc, "pred": y_pred}

plt.figure(figsize=(8,5))
sns.barplot(x=list(results.keys()), y=[r["acc"] for r in results.values()], palette="viridis")
plt.title("Сравнение точности моделей", fontsize=14)
plt.ylabel("Accuracy")
plt.ylim(0, 1)
plt.xticks(rotation=20)
plt.show()

for name, res in results.items():
    cm = confusion_matrix(y_test, res["pred"])
    disp = ConfusionMatrixDisplay(cm, display_labels=np.unique(y))
    disp.plot(cmap="Blues", values_format='d')
    plt.title(f"Confusion Matrix: {name}")
    plt.show()

plt.figure(figsize=(35, 15))
plot_tree(results["Decision Tree"]["model"],
          feature_names=X.columns,
          class_names=[str(c) for c in np.unique(y)],
          filled=True, rounded=True, fontsize=8)
plt.title("Decision Tree Structure")
plt.show()

def plot_feature_importance(model, model_name):
    if hasattr(model, "feature_importances_"):
        importances = model.feature_importances_
        indices = np.argsort(importances)[::-1]
        plt.figure(figsize=(8, 4))
        sns.barplot(x=importances[indices], y=np.array(X.columns)[indices], palette="mako")
        plt.title(f"Feature Importance: {model_name}")
        plt.xlabel("Importance")
        plt.ylabel("Feature")
        plt.show()

for name, res in results.items():
    plot_feature_importance(res["model"], name)

print("Сравнение точности:")
for name, res in results.items():
    print(f"{name:15s} — Accuracy: {res['acc']:.4f}")

best_model = max(results.items(), key=lambda x: x[1]['acc'])
print(f"\nЛучшая модель: {best_model[0]} с точностью {best_model[1]['acc']:.4f}")

from sklearn.metrics import classification_report

print("\n=== Classification Reports ===")
for name, res in results.items():
    print(f"\n--- {name} ---")
    print(classification_report(y_test, res["pred"], target_names=[str(c) for c in np.unique(y)]))