# Generated by Django 5.1.1 on 2024-09-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Информация_о_накладных',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numНакладной', models.IntegerField()),
                ('Ответственное_Лицо', models.CharField(max_length=255)),
                ('Дата_Отгрузки', models.DateField()),
                ('Средний_Балл', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Накладные',
            fields=[
                ('numНакладной', models.AutoField(primary_key=True, serialize=False)),
                ('numТовара', models.IntegerField()),
                ('Количество', models.IntegerField(default=0)),
                ('Стоимость', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Товары',
            fields=[
                ('numТовара', models.AutoField(primary_key=True, serialize=False)),
                ('Наименование', models.CharField(max_length=255)),
                ('Единица_измерения', models.CharField(max_length=255)),
                ('Цена', models.IntegerField(default=0)),
            ],
        ),
    ]
